services:
  app:
    image: marcoexexx/tomorrow-challenge-app:beta
    ports:
      - "4173"
    networks:
      - tomorrow-challenge-network
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tomorrow-challenge-network

networks:
  tomorrow-challenge-network:
    driver: bridge
