run:
	docker-compose -f ./docker-compose.yaml pull
	docker-compose -f ./docker-compose.yaml up -d --build

dev:
	docker-compose -f ./docker-compose.local.yaml pull
	docker-compose -f ./docker-compose.local.yaml up --build
