services:
  app:
    image: marcoexexx/tomorrow-challenge-api-app:0.1.0
    container_name: tomorrow-challenge-api-app
    ports:
      - 8000:8000
      - 5555:5555
    networks:
      - tomorrow-challenge-api-network
    depends_on:
      - postgresdb
      - redis
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: tomorrow-challenge-api-redis
    env_file:
      - ./.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - tomorrow-challenge-api-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgresdb:
    image: postgres:latest
    env_file:
      - ./.env
    container_name: tomorrow-challenge-api-postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
    networks:
      - tomorrow-challenge-api-network

volumes:
  db:
  cache:

networks:
  tomorrow-challenge-api-network:
    driver: bridge
